# generator/packer.py

import zipfile
from io import BytesIO


def build_full_mod(code):
    buffer = BytesIO()

    with zipfile.ZipFile(buffer, "a") as z:
        z.writestr("modmain.lua", code)

        z.writestr("scripts/prefabs/boss.lua", code)

        z.writestr("modinfo.lua", """
name = "AI Generated Boss"
description = "Generated by AI"
author = "AI"
version = "1.0"
""")

    return buffer.getvalue()