import streamlit as st
import json
import zipfile
from io import BytesIO

from llm.qwen_client import design_with_llm
from bridge.intent_builder import build_intent_from_design
from parser.recommender import recommend


# ===== 页面配置 =====
st.set_page_config(page_title="AI Mod Generator", layout="wide")

st.title("🎮 AI 饥荒 Mod 生成器")


# ===== Session 初始化（核心状态管理）=====
if "messages" not in st.session_state:
    st.session_state.messages = []   # 聊天记录

if "history" not in st.session_state:
    st.session_state.history = []    # 输入历史


# ===== Sidebar 历史记录 =====
with st.sidebar:
    st.title("📜 历史记录")

    for i, item in enumerate(st.session_state.history):
        if st.button(f"{i+1}. {item[:20]}..."):
            st.session_state.messages.append({
                "role": "user",
                "content": item
            })


# ===== 构建多轮上下文（关键）=====
def build_messages(user_input):
    msgs = [
        {"role": "system", "content": "你是一个游戏Mod设计AI"}
    ]

    # 保留最近6轮对话（避免token爆炸）
    for m in st.session_state.messages[-6:]:
        if m["role"] == "user":
            msgs.append({"role": "user", "content": m["content"]})
        else:
            msgs.append({
                "role": "assistant",
                "content": json.dumps(m["content"]["design"])
            })

    msgs.append({"role": "user", "content": user_input})
    return msgs


# ===== 生成ZIP（多文件下载）=====
def build_mod_zip(code):
    zip_buffer = BytesIO()

    with zipfile.ZipFile(zip_buffer, "a") as z:
        z.writestr("modmain.lua", code)

        z.writestr("modinfo.lua", """
name = "AI Generated Mod"
description = "Generated by AI"
author = "AI"
version = "1.0"
""")

    return zip_buffer.getvalue()


# ===== 输入框 =====
user_input = st.chat_input("输入你的想法（例如：月亮Boss）")


# ===== 处理用户输入 =====
if user_input:
    # 保存历史
    st.session_state.history.append(user_input)

    # 构建上下文
    messages = build_messages(user_input)

    # 调用 LLM
    design_str = design_with_llm(messages)

    try:
        design = json.loads(design_str)
    except:
        st.error("LLM返回JSON格式错误")
        st.stop()

    # 构建 intent
    intent = build_intent_from_design(design)

    # 推荐
    result = recommend(intent)

    # 保存对话
    st.session_state.messages.append({
        "role": "user",
        "content": user_input
    })

    st.session_state.messages.append({
        "role": "ai",
        "content": {
            "design": design,
            "result": result
        }
    })


# ===== 渲染聊天界面 =====
for msg in st.session_state.messages:

    if msg["role"] == "user":
        with st.chat_message("user"):
            st.write(msg["content"])

    else:
        with st.chat_message("assistant"):

            design = msg["content"]["design"]
            result = msg["content"]["result"]

            # ===== 设计概念 =====
            st.markdown("### 🧠 设计概念")
            st.success(design.get("concept", ""))

            # ===== AI建议 =====
            st.markdown("### ❓ AI建议")
            for q in design.get("questions", []):
                st.info(q)

            # ===== API & 步骤 =====
            col1, col2 = st.columns(2)

            with col1:
                st.markdown("### 🔧 API推荐")
                st.code("\n".join(result.get("apis", [])))

            with col2:
                st.markdown("### 📌 实现步骤")
                for i, step in enumerate(result.get("steps", []), 1):
                    st.write(f"{i}. {step}")

            # ===== Lua代码 =====
            code = result.get("code", "-- no code")

            st.markdown("### 💻 Lua代码")
            st.code(code, language="lua")

            # ===== 下载ZIP =====
            zip_data = build_mod_zip(code)

            st.download_button(
                label="📦 下载完整Mod",
                data=zip_data,
                file_name="mod.zip",
                mime="application/zip"
            )