import streamlit as st
import json
import zipfile
from io import BytesIO

from llm.qwen_client import design_with_llm
from bridge.intent_builder import build_intent_from_design
from parser.recommender import recommend


# ===== 页面配置 =====
st.set_page_config(page_title="AI Mod Generator", layout="wide")
st.title("🎮 AI 饥荒 Mod 生成器")


# ===== Session 初始化 =====
if "mode" not in st.session_state:
    st.session_state.mode = None

if "explore_messages" not in st.session_state:
    st.session_state.explore_messages = []

if "final_design" not in st.session_state:
    st.session_state.final_design = None


# ===== 工具函数 =====

# 📦 打包mod
def build_mod_zip(code):
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "a") as z:
        z.writestr("modmain.lua", code)
        z.writestr("modinfo.lua", """
name = "AI Generated Mod"
description = "Generated by AI"
author = "AI"
version = "1.0"
""")
    return buffer.getvalue()


# 🧠 构建探索模式上下文
def build_explore_messages(user_input):
    msgs = [{"role": "system", "content": "你是一个游戏Mod设计AI，帮助用户逐步明确Boss设计，不要直接生成代码"}]

    for m in st.session_state.explore_messages:
        msgs.append(m)

    msgs.append({"role": "user", "content": user_input})
    return msgs


# ===== 模式选择 =====
st.subheader("请选择模式")

col1, col2 = st.columns(2)

with col1:
    if st.button("🚀 快速生成（已有完整想法）"):
        st.session_state.mode = "fast"

with col2:
    if st.button("🧠 探索设计（逐步构思）"):
        st.session_state.mode = "explore"


# =========================
# 🟢 模式1：快速生成
# =========================
if st.session_state.mode == "fast":

    st.header("🚀 快速生成模式")

    user_input = st.text_area("请输入完整的Boss/Mod设计想法")

    if st.button("生成Mod"):
        if not user_input:
            st.warning("请输入内容")
        else:
            design_str = design_with_llm(user_input)

            try:
                design = json.loads(design_str)
            except:
                st.error("LLM返回JSON错误")
                st.stop()

            intent = build_intent_from_design(design)
            result = recommend(intent)

            st.success("🧠 设计概念")
            st.write(design.get("concept"))

            st.subheader("🔧 API推荐")
            st.write(result.get("apis", []))

            st.subheader("📌 实现步骤")
            for i, step in enumerate(result.get("steps", []), 1):
                st.write(f"{i}. {step}")

            code = result.get("code", "-- no code")

            st.subheader("💻 Lua代码")
            st.code(code, language="lua")

            zip_data = build_mod_zip(code)

            st.download_button(
                "📦 下载Mod",
                data=zip_data,
                file_name="mod.zip",
                mime="application/zip"
            )


# =========================
# 🔵 模式2：探索设计（多轮AI）
# =========================
if st.session_state.mode == "explore":

    st.header("🧠 探索设计模式")

    user_input = st.chat_input("描述你的想法（可以很模糊）")

    if user_input:
        st.session_state.explore_messages.append({
            "role": "user",
            "content": user_input
        })

        messages = build_explore_messages(user_input)

        reply = design_with_llm(messages)

        st.session_state.explore_messages.append({
            "role": "assistant",
            "content": reply
        })

    # ===== 渲染聊天 =====
    for msg in st.session_state.explore_messages:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    # ⭐ 进入生成阶段
    if st.button("✅ 设计完成，开始生成Mod"):
        st.session_state.mode = "generate"


# =========================
# ⚙️ 模式3：生成阶段（统一流程）
# =========================
if st.session_state.mode == "generate":

    st.header("⚙️ Mod生成结果")

    messages = [
        {"role": "system", "content": "你是一个游戏Mod设计AI，请输出最终JSON设计"}
    ]

    messages.extend(st.session_state.explore_messages)

    design_str = design_with_llm(messages)

    try:
        design = json.loads(design_str)
    except:
        st.error("生成失败（JSON错误）")
        st.stop()

    intent = build_intent_from_design(design)
    result = recommend(intent)

    st.success("🧠 最终设计")
    st.write(design.get("concept"))

    st.subheader("🔧 API推荐")
    st.write(result.get("apis", []))

    st.subheader("📌 实现步骤")
    for i, step in enumerate(result.get("steps", []), 1):
        st.write(f"{i}. {step}")

    code = result.get("code", "-- no code")

    st.subheader("💻 Lua代码")
    st.code(code, language="lua")

    zip_data = build_mod_zip(code)

    st.download_button(
        "📦 下载完整Mod",
        data=zip_data,
        file_name="mod.zip",
        mime="application/zip"
    )
